### ISSUE TITLE
[Feature] Accept value

### ISSUE THREAD

**Issue by hiradary** [amin3mej/telegram-observer-bot#26]
By "Accept Value" I mean I want a feature that enables us to, aside from basic commands - that are so static - send value  to be processed by bot.

For example :
!hello Hirad    // -> Hello Hirad

**Comment by amin3mej** [comment]
@hiradary Pull request is welcome. What do you think about fixing this?

**Comment by hiradary** [comment]
@amin3mej Well, I've never written a single line of PHP in my life :) But let me see if I can reverse-engineer it.

**Comment by hiradary** [comment]
I actually can't remember why I wanted this feature to be implemented in the first place :))
