### ISSUE TITLE
حذف محتوای طولانی

### ISSUE THREAD

**Issue by Sosha1996** [amin3mej/telegram-observer-bot#41]
قابلیتی به ربات اضافه بشه که اگر پیامی خیلی طولانی بود، حذفش کنه و اون رو سریع در سرویس‌های پیستبین قرار بده و لینکش رو ریپلای کنه به فردی که متن طولانی رو ارسال کرده.
میشه یه توضیحی هم توی متن ریپلای شده برای اون کاربر نوشت.

**Comment by par6n** [comment]
Bot must only reduce the messages with long codes, not long texts.

In my opinion, I'd say we delete all long messages, since they're not gonna be answered and Telegram groups aren't suitable for these kind of messages, but this depends on group's admins' opinions.
