### ISSUE TITLE
تغییر واژه "قلم" به زبان

### ISSUE THREAD

**Issue by se7enf98** [amin3mej/telegram-observer-bot#50]
سلام
به نظرم توی مواقعی که ربات به پیام‌های غیرفارسی ایراد می‌گیره، بهتره توی متن پیام به جای واژه "قلم" از زبان استفاده بشه.
فکر می‌کنم "قلم" معادل فارسی "فونت" درنظر گرفته میشه
با تشکر :)

**Comment by amin3mej** [comment]
سلام

لطفا اصلاحش کنید و مرج‌ریکوئست بفرستید.
