### ISSUE TITLE
نیاز به فهرست قابلیت‌های روبات

### ISSUE THREAD

**Issue by NabiKAZ** [amin3mej/telegram-observer-bot#54]
<div dir=rtl>

در توضیحات این پروژه آمده:

> سورس یک ربات تلگرام که گروه شما را مشاهده می‌کند و به مدیرها کمک می‌کند تا راحت‌تر مدیریت کنند.

«راحت‌تر مدیریت کنند» یعنی چه؟
آیا حداقل نیاز نیست به اختصار، قابلیت‌ها، ویژگی‌ها و توانایی‌های این روبات را فهرست‌وار بیاورید تا با آگاهی بیش‌تر مورد استفاده قرار بگیرد؟

**Comment by amin3mej** [comment]
یک سری از اماکانات رو اینجا براتون لیست می‌کنم مانند: 
- جلوگیری از افزودن ربات (API bots) توسط کاربران
- امکان ساخت لینک ورود موقت به گروه
- اصلاح غلط‌های نگارشیِ کلمه «اوبونتو»
- اخراج افرادی که برنامه قابل نصب اندروید (apk) داخل گروه ارسال می‌کنند.
- امکان ارسال سریع پیام‌های از پیش تعیین شده.
- امکان گزارش یک پیام به مدیرهای گروه
